apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "appName." . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "appName.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "appName.name" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: "app"
                operator: In
                values: 
                - {{ include "appName.name" . }}
            topologyKey: "kubernetes.io/hostname"
